# Generated by Django 5.1.1 on 2024-10-12 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo_list',
            old_name='copleted',
            new_name='completed',
        ),
    ]
