# Generated by Django 5.1.1 on 2024-10-13 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0002_rename_copleted_todo_list_completed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Todo_list',
        ),
    ]
